//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoAvaliacao
    {
        public int PessoaId { get; set; }
        public int AvaliacaoId { get; set; }
        public int PessoaCadastrou { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<int> DuplaId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Avaliacoes Avaliacoes { get; set; }
    }
}
