//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Avaliacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacoes()
        {
            this.AlunoAvaliacao = new HashSet<AlunoAvaliacao>();
            this.GrupoQuestao = new HashSet<GrupoQuestao>();
            this.Questao = new HashSet<Questao>();
        }
    
        public int AvaliacaoId { get; set; }
        public int PessoaId { get; set; }
        [Required]
        [MaxLength(60, ErrorMessage ="maximo de 60 Caracteres")]
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        [Required]
        public int TurmaId { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DataAvaliacao { get; set; }
        public Nullable<bool> dupla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlunoAvaliacao> AlunoAvaliacao { get; set; }
        public virtual Status Status { get; set; }
        public virtual Turma Turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoQuestao> GrupoQuestao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questao> Questao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
