//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurmaPessoa
    {
        public int PessoaId { get; set; }
        public int TurmaId { get; set; }
        public int pessoaCadastrou { get; set; }
        public System.DateTime DataHora { get; set; }
        public string Observecao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
